name : deploy HMS application

on:
  push:
    branches:
     -main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Set up Node Js
      users: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build HMS application
      run: npm run build